// Code generated by protoc-gen-go. DO NOT EDIT.
// source: routetable.proto

/*
Package routetable is a generated protocol buffer package.

It is generated from these files:
	routetable.proto

It has these top-level messages:
	Route
	RoutingTable
*/
package routetable

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Define a route
type Route struct {
	Dest      string `protobuf:"bytes,1,opt,name=dest" json:"dest,omitempty"`
	Mask      string `protobuf:"bytes,2,opt,name=mask" json:"mask,omitempty"`
	Nh        string `protobuf:"bytes,3,opt,name=nh" json:"nh,omitempty"`
	Metric    int32  `protobuf:"varint,4,opt,name=metric" json:"metric,omitempty"`
	Interface string `protobuf:"bytes,5,opt,name=interface" json:"interface,omitempty"`
}

func (m *Route) Reset()                    { *m = Route{} }
func (m *Route) String() string            { return proto.CompactTextString(m) }
func (*Route) ProtoMessage()               {}
func (*Route) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Route) GetDest() string {
	if m != nil {
		return m.Dest
	}
	return ""
}

func (m *Route) GetMask() string {
	if m != nil {
		return m.Mask
	}
	return ""
}

func (m *Route) GetNh() string {
	if m != nil {
		return m.Nh
	}
	return ""
}

func (m *Route) GetMetric() int32 {
	if m != nil {
		return m.Metric
	}
	return 0
}

func (m *Route) GetInterface() string {
	if m != nil {
		return m.Interface
	}
	return ""
}

// Define a routing table
type RoutingTable struct {
	Routes []*Route `protobuf:"bytes,1,rep,name=routes" json:"routes,omitempty"`
}

func (m *RoutingTable) Reset()                    { *m = RoutingTable{} }
func (m *RoutingTable) String() string            { return proto.CompactTextString(m) }
func (*RoutingTable) ProtoMessage()               {}
func (*RoutingTable) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RoutingTable) GetRoutes() []*Route {
	if m != nil {
		return m.Routes
	}
	return nil
}

func init() {
	proto.RegisterType((*Route)(nil), "routetable.Route")
	proto.RegisterType((*RoutingTable)(nil), "routetable.RoutingTable")
}

func init() { proto.RegisterFile("routetable.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 173 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0xca, 0x2f, 0x2d,
	0x49, 0x2d, 0x49, 0x4c, 0xca, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x42, 0x88,
	0x28, 0x95, 0x72, 0xb1, 0x06, 0x81, 0x78, 0x42, 0x42, 0x5c, 0x2c, 0x29, 0xa9, 0xc5, 0x25, 0x12,
	0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0x36, 0x48, 0x2c, 0x37, 0xb1, 0x38, 0x5b, 0x82, 0x09,
	0x22, 0x06, 0x62, 0x0b, 0xf1, 0x71, 0x31, 0xe5, 0x65, 0x48, 0x30, 0x83, 0x45, 0x98, 0xf2, 0x32,
	0x84, 0xc4, 0xb8, 0xd8, 0x72, 0x53, 0x4b, 0x8a, 0x32, 0x93, 0x25, 0x58, 0x14, 0x18, 0x35, 0x58,
	0x83, 0xa0, 0x3c, 0x21, 0x19, 0x2e, 0xce, 0xcc, 0xbc, 0x92, 0xd4, 0xa2, 0xb4, 0xc4, 0xe4, 0x54,
	0x09, 0x56, 0xb0, 0x72, 0x84, 0x80, 0x92, 0x25, 0x17, 0x0f, 0xc8, 0xda, 0xcc, 0xbc, 0xf4, 0x10,
	0x90, 0x33, 0x84, 0x34, 0xb9, 0xd8, 0xc0, 0x8e, 0x2a, 0x96, 0x60, 0x54, 0x60, 0xd6, 0xe0, 0x36,
	0x12, 0xd4, 0x43, 0x72, 0x35, 0xd8, 0x81, 0x41, 0x50, 0x05, 0x49, 0x6c, 0x60, 0x4f, 0x18, 0x03,
	0x02, 0x00, 0x00, 0xff, 0xff, 0x2e, 0x76, 0x88, 0xf4, 0xd8, 0x00, 0x00, 0x00,
}
