# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: routetable.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='routetable.proto',
  package='routetable',
  syntax='proto3',
  serialized_pb=_b('\n\x10routetable.proto\x12\nroutetable\"R\n\x05Route\x12\x0c\n\x04\x64\x65st\x18\x01 \x01(\t\x12\x0c\n\x04mask\x18\x02 \x01(\t\x12\n\n\x02nh\x18\x03 \x01(\t\x12\x0e\n\x06metric\x18\x04 \x01(\x05\x12\x11\n\tinterface\x18\x05 \x01(\t\",\n\x0b\x44\x65stination\x12\x0f\n\x07network\x18\x01 \x01(\t\x12\x0c\n\x04mask\x18\x02 \x01(\t\"\x19\n\x06Result\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32z\n\x06Router\x12\x38\n\x08GetRoute\x12\x17.routetable.Destination\x1a\x11.routetable.Route\"\x00\x12\x36\n\tAddRoutes\x12\x11.routetable.Route\x1a\x12.routetable.Result\"\x00(\x01\x62\x06proto3')
)




_ROUTE = _descriptor.Descriptor(
  name='Route',
  full_name='routetable.Route',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dest', full_name='routetable.Route.dest', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mask', full_name='routetable.Route.mask', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nh', full_name='routetable.Route.nh', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='metric', full_name='routetable.Route.metric', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='interface', full_name='routetable.Route.interface', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=114,
)


_DESTINATION = _descriptor.Descriptor(
  name='Destination',
  full_name='routetable.Destination',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='network', full_name='routetable.Destination.network', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mask', full_name='routetable.Destination.mask', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=160,
)


_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='routetable.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='routetable.Result.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=162,
  serialized_end=187,
)

DESCRIPTOR.message_types_by_name['Route'] = _ROUTE
DESCRIPTOR.message_types_by_name['Destination'] = _DESTINATION
DESCRIPTOR.message_types_by_name['Result'] = _RESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Route = _reflection.GeneratedProtocolMessageType('Route', (_message.Message,), dict(
  DESCRIPTOR = _ROUTE,
  __module__ = 'routetable_pb2'
  # @@protoc_insertion_point(class_scope:routetable.Route)
  ))
_sym_db.RegisterMessage(Route)

Destination = _reflection.GeneratedProtocolMessageType('Destination', (_message.Message,), dict(
  DESCRIPTOR = _DESTINATION,
  __module__ = 'routetable_pb2'
  # @@protoc_insertion_point(class_scope:routetable.Destination)
  ))
_sym_db.RegisterMessage(Destination)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), dict(
  DESCRIPTOR = _RESULT,
  __module__ = 'routetable_pb2'
  # @@protoc_insertion_point(class_scope:routetable.Result)
  ))
_sym_db.RegisterMessage(Result)



_ROUTER = _descriptor.ServiceDescriptor(
  name='Router',
  full_name='routetable.Router',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=189,
  serialized_end=311,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetRoute',
    full_name='routetable.Router.GetRoute',
    index=0,
    containing_service=None,
    input_type=_DESTINATION,
    output_type=_ROUTE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AddRoutes',
    full_name='routetable.Router.AddRoutes',
    index=1,
    containing_service=None,
    input_type=_ROUTE,
    output_type=_RESULT,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ROUTER)

DESCRIPTOR.services_by_name['Router'] = _ROUTER

# @@protoc_insertion_point(module_scope)
